### ISSUE TITLE
Cannot make Molvec work with java version 11

### ISSUE THREAD

**Issue by jasondbiggs** [ncats/molvec#1]
We are moving to java version 11, company wide, and I can no longer use Molvec.  Is this reproducible by anyone else?  Any clue what is failing here?

Here is the output from calling molvec in the command line, first using java 1.8 and then using java 11.  The circleAromatic.png file is from the test suite

```

> java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

> java -jar molvec-0.9.4-jar-with-dependencies.jar -f circleAromatic.png 

  Molvec0110301913092D

 13 14  0  0  0  0  0  0  0  0999 V2000
    0.8594   -0.9898    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0011   -0.4943    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0011    0.4969    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8573   -0.9898    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8594    0.9925    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8594    1.9836    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8573    0.9925    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8573    1.9836    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8594   -1.9810    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.7178    0.4969    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.7178   -0.4943    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7157   -0.4943    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7157    0.4969    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  4  0
  2  3  4  0
  2  4  1  0
  3  5  4  0
  3  7  1  0
  1  9  1  0
 12 13  1  0
  5  6  1  0
  5 10  4  0
  7  8  1  0
  7 13  1  0
  4 12  1  0
  1 11  4  0
 10 11  4  0
M  END

// Switch to java 11
> export JAVA_HOME=$(/usr/libexec/java_home -v 11)
> java -version

java version "11.0.5" 2019-10-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.5+10-LTS, mixed mode)

> java -jar molvec-0.9.4-jar-with-dependencies.jar -f circleAromatic.png 

  Molvec0110301913092D

  0  0  0  0  0  0  0  0  0  0999 V2000
M  END
```

**Comment by jasondbiggs** [comment]
In the above, I was using the jar file I generated using the old version of java. Trying a clean maven build with java 11 fails due to test failures.  Attaching the log from the maven build using java 11

[mvn_output.txt](https://github.com/ncats/molvec/files/3790787/mvn_output.txt)

**Comment by caodac** [comment]
Hi Jason, thank you for the email and bug report. Believe it or not, we've never tried on Java >8. We'll take a look and get back to you. 
Thanks,
Trung

**Comment by tylerperyea** [comment]
Hi Jason,

I believe the fix staged in this pull request (#2 ) should take care of this issue. I have more written about it there, but basically it seems the default low-level reads for alpha in certain color spaces has changed between java8 and java11.

Thanks!

Tyler

**Comment by jasondbiggs** [comment]
Thank you for the quick fix @tylerperyea, that definitely has things back up and running.  

I have to say again that Molvec is very impressive. 

If I encounter other issues or bugs would you like me to use the github issues like this, or send an email to the address listed on the readme file?

**Comment by caodac** [comment]
That's great, Jason! I think filing github issues is best. We only provide contact information for legacy reasons when we were hosting the code on our old gitlab repo.

**Comment by tylerperyea** [comment]
Yeah, I think this issue demonstrates that transparency is pretty important. =D

**Comment by dkatzel-ncats** [comment]
Code fix has been pushed to maven central as molvec 0.9.5
