### ISSUE TITLE
[Feature request] Bounding box

### ISSUE THREAD

**Issue by dbdr** [ncats/molvec#6]
This seems very promising, congrats!

It would be very useful to expose in the API the bounding box of each molecule in terms of the original image coordinates. One possibility would be to (optionally?) use SDF formal instead of MOL, and simply append:
```
M END
> BoundingBox
X1 Y1 X2 Y2
```
However an API that returns a list of Molecule objects would also be fine, with something like:
```
class Molecule {
    String mol;
    int x1, y1, x2, y2;
    // Other metadata?
}
```

**Comment by dbdr** [comment]
Another, maybe simpler, option: (optionally) keep the atom coordinates in the original coordinate system, without scaling nor centering. It's trivial for the user to calculate the bounding box based on that.

**Comment by caodac** [comment]
Thanks for the feature request. This seems pretty straightforward. Can I ask what's the use case for this? Since Molvec currently isn't a general page reader (yet), it's likely the case that you're using a cropped image of the structure as input, in which case you would already have access to the original image coordinates?

**Comment by tylerperyea** [comment]
It's worth noting that the centering/scaling only happens at the very last step of the chemical ocr. If you want to get the original coordinates now, you can do this via the java API, but it's just a little involved:

```
StructureImageExtractor sie = new StructureImageExtractor(image);
ConnectionTable ct=sie.getCtab();
//this will get the bounding box by looking at the nodes (the coordinates are in original image pixels)
	Rectangle2D rect=this.getNodes()
				             .stream()
				             .map(n->n.getPoint())
				             .collect(GeomUtil.convexHull())
				             .getBounds2D();
String mol=ct.toMol();
//do something with the rect
//do something with the mol
```

I agree though that abstracting the return format in the Java API to be a molecule with some wrapped statistics isn't a bad idea at all. The ConnectionTable does get you this, but is a little removed from the real molecular understanding for sure.

**Comment by tylerperyea** [comment]
Like @caodac said though, while this will _usually_ give the pixels of the image, the cropping function of MolVec is very pedestrian and won't tend to be good at isolating a molecule in a larger context. Moreover, it _sometimes_ will preprocess (pre-scale, pre-crop) the image, meaning that the bounding box above will not _always_ be the same one that makes sense in the original image.

**Comment by dbdr** [comment]
@caodac Thanks for the precision. In the case where the image contains two different molecules, I expected the MOL string would separate them, since that's possible in that format. However, if I read the code correctly there will always be a single one. However it's still possible for the client to do the separation as post-processing, so that getting the atom coordinates in terms of the original image is still useful.

What I used as a workaround is to avoid the scaling and recentering by calling:

```ctab.toMol(ctab.getAverageBondLength(), false, true);```

Would that be incorrect in the case of the proprocessing you mention, @tylerperyea ?

**Comment by tylerperyea** [comment]
Hmm ... yes, I think that would work. That's an interesting way to do it. I'm not positive whether it would work if there are no bonds, but that is a very rare case with MolVec. The final `true` is probably not necessary, but should make the names of groups be closer to the rendered image too. Have you tried it and double checked that it seems to give the same pixel values? 

BTW, you're right, MolVec does not give sets of molecules, but just one large molecule which may contain multiple disconnected components inside.

**Comment by dkatzel-ncats** [comment]
in the new version of Molvec 0.9.8, there are new API calls to get a `MolvecResult` object instead of just a String of the molfile.  This new object has not only methods to get the molfile and sdfile but it also has a method to get the `Rectangle2D` of the image bounding box like you wanted:

```java
MolvecResult result = Molvec.ocr(f, new MolvecOptions());

//the result returns Optionals incase there was an error
Rectangle2D boundingBox = result.getOriginalBoundingBox().get();

//you can also get the molfile like this:
String mol = result.getMolfile().get();
```

Thanks for creating this feature request it showed there was a need for an improved API. closing ticket
